SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - NewsletterSiteConfig
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - NewsletterContentControllerExtension
SilverStripe\Control\Director:
  rules:
    'newsletterlinks/$Hash': 'TrackLinkController'
    'unsubscribe//$Action/$ValidateHash/$IDs': 'UnsubscribeController'
