SilverStripe\Security\Member:
  extensions:
    - Newsletter\Extensions\RecipientExtension
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Newsletter\Extensions\NewsletterSiteConfig
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Newsletter\Extensions\NewsletterContentControllerExtension
SilverStripe\Control\Director:
  rules:
    'newsletter//$Action/$ID': 'Newsletter\Controller\NewsletterFeedbackController'
    'newsletterlinks/$Hash': 'Newsletter\Controller\TrackLinkController'
    'unsubscribe//$Action/$ValidateHash/$IDs': 'Newsletter\Controller\UnsubscribeController'

SilverStripe\Admin\LeftandMain:
  admin_themes:
    - 'newsletter-admin'
