SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - NewsletterSiteConfig
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - NewsletterContentControllerExtension
SilverStripe\Control\Director:
  rules:
    'newsletterlinks/$Hash': 'Newsletter\Controller\TrackLinkController'
    'unsubscribe//$Action/$ValidateHash/$IDs': 'Newsletter\Controller\UnsubscribeController'
