Member:
  extensions:
    - RecipientExtension
SiteConfig:
  extensions:
    - NewsletterSiteConfig
ContentController:
  extensions:
    - NewsletterContentControllerExtension
Director:
  rules:
    'newsletterlinks/$Hash': 'TrackLinkController'
    'unsubscribe//$Action/$ValidateHash/$IDs': 'UnsubscribeController'
