SiteConfig:
  extensions:
    - NewsletterSiteConfig
ContentController:
  extensions:
    - NewsletterContentControllerExtension
Director:
  rules:
    'newsletterlinks/$Hash': 'TrackLinkController'
    '$Lang/unsubscribe//$Action/$ValidateHash/$IDs': 'UnsubscribeController'